spring.application.name=camel-orders
server.port=${SERVER_PORT:8080}
camel.springboot.main-run-controller=true
camel.springboot.jmx-enabled=false
camel.main.additional-sensitive-keywords=password,secret,token,api-key,credential
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized
management.health.defaults.enabled=true
camel.component.platform-http.match-on-uri-prefix=true
